name: clean_network_annotations
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
